export const GET_FPAYMENTS = "GET_FPAYMENTS";
export const LOADING_GET_FPAYMENTS = "LOADING_GET_FPAYMENTS";
export const SET_SELECTED_FORPAYMENT = "SET_SELECTED_FORPAYMENT";


export const FPAYMENTS_ERROR = "FPAYMENTS_ERROR";

