export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const SET_SELECTED_EMPLOYEE = "SET_SELECTED_EMPLOYEE";
export const UPDATE_EMPLOYEE_PASSWORD = "UPDATE_EMPLOYEE_PASSWORD";

export const EMPLOYEES_ERROR = "EMPLOYEES_ERROR";
