export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_PASSWORD = "UPDATE_EMPLOYEE_PASSWORD";
export const SET_SELECTED_EMPLOYEE = "SET_SELECTED_EMPLOYEE";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_FORM_PASSWORD = "LOADING_FORM_PASSWORD";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const EMPLOYEES_ERROR = "EMPLOYEES_ERROR";

