export const GET_CURRENCY = "GET_CURRENCY";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_CURRENCY = "LOADING_CURRENCY";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const CURRENCY_ERROR = "CURRENCY_ERROR";

