export const GET_BILLS = "GET_BILLS";
export const SET_SELECTED_BILL = "SET_SELECTED_BILL";
export const SET_SELECTED_SELECT = "SET_SELECTED_SELECT";
export const LOADING_GET_BILL = "LOADING_GET_BILL";
export const LOADING_CANCEL_BILL = "LOADING_CANCEL_BILL";
export const BILL_CLEAN_STATE = "BILL_CLEAN_STATE";
export const CANCEL_BILL = "CANCEL_BILL";
export const BILLS_ERROR = "BILLS_ERROR";

export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";