export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const PRODUCTS_ERROR = "PRODUCTS_ERROR";