export const SET_PATIENT = "SET_PATIENT";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_GET_PATIENT = "LOADING_GET_PATIENT";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const PATIENT_ERROR = "PATIENT_ERROR";

