export const GET_NPAYMENTS = "GET_NPAYMENTS";
export const LOADING_GET_NPAYMENTS = "LOADING_GET_NPAYMENTS";
export const SET_SELECTED_NATPAYMENT = "SET_SELECTED_NATPAYMENT";


export const NPAYMENTS_ERROR = "NPAYMENTS_ERROR";

