export const GET_CLIENT = "GET_CLIENT";
export const LOADING_CLIENT = "LOADING_CLIENT";
export const CLEAN_REGISTERBOX = "CLEAN_REGISTERBOX";
export const ADD_TO_LIST = "ADD_TO_LIST";
export const TAKEOUT = "TAKEOUT";
export const LOADING_PRODUCT_REGISTERBOX = "LOADING_PRODUCT_REGISTERBOX";
export const GET_PRODUCT_REGISTERBOX = "GET_PRODUCT_REGISTERBOX";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";

// export const GET_PRODUCTS = "GET_PRODUCTS";
// export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
// export const SET_SELECTED_SELECT = "SET_SELECTED_SELECT";
// export const LOADING_FORM = "LOADING_FORM";
// export const LOADING_PRODUCT = "LOADING_PRODUCT";
// export const LOADING_PRODUCT_PRICES = "LOADING_PRODUCT_PRICES";
// export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
// export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";
// export const INVENTORY_CLEAN_STATE = "INVENTORY_CLEAN_STATE";
// export const SET_SELECTED_SEARCHFORM ="SET_SELECTED_SEARCHFORM";

// export const PRODUCTS_ERROR = "PRODUCTS_ERROR";