export const GET_CLIENT = "GET_CLIENT";
export const CREATE_CLIENT = "CREATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT";
export const LOADING_FORM = "LOADING_FORM";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const CLIENTS_ERROR = "CLIENTS_ERROR";

