export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const SET_SELECTED_PATIENT = "SET_SELECTED_PATIENT";
export const SET_SELECTED_SELECT = "SET_SELECTED_SELECT";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_GET_PATIENT = "LOADING_GET_PATIENT";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";
export const CLEAN_STATE = "CLEAN_STATE";

export const PATIENT_ERROR = "PATIENT_ERROR";

