export const SET_VISIBLE = "SET_VISIBLE";
export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const SET_SELECTED_APPOIMENT = "SET_SELECTED_APPOIMENT";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_GET_APPOINTMENTS = "LOADING_GET_APPOINTMENTS";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const APPOINTMENT_ERROR = "APPOINTMENT_ERROR";

