export const SET_VISIBLE_TOOTH_OPTIONS = "SET_VISIBLE_TOOTH_OPTIONS";
export const SET_SELECTED_TOOTH = "SET_SELECTED_TOOTH";
export const LOADING_GET_THEE = "LOADING_GET_THEE";
export const SET_ODTG_EDITABLE = "SET_ODTG_EDITABLE";

// export const SET_SELECTED_APPOIMENT = "SET_SELECTED_APPOIMENT";
export const LOADING_CREATE_UPDATE_TOOTH = "LOADING_CREATE_UPDATE_TOOTH";
// export const LOADING_GET_APPOINTMENTS = "LOADING_GET_APPOINTMENTS";
// export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
// export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const THEE_ERROR = "THEE_ERROR";

