export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const SET_SELECTED_SELECT = "SET_SELECTED_SELECT";
export const SET_SELECTED_SEARCHFORM = "SET_SELECTED_SEARCHFORM";
export const LOADING_FORM = "LOADING_FORM";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const LOADING_PRODUCT_PRICES = "LOADING_PRODUCT_PRICES";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";
export const INVENTORY_CLEAN_STATE = "INVENTORY_CLEAN_STATE";

export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
