export const ADD_PAYMENTMADE = "ADD_PAYMENTMADE";
export const SET_SELECTED_PAYMENTMADE = "SET_SELECTED_PAYMENTMADE";
export const DELETE_PAYMENTMADE = "DELETE_PAYMENTMADE";
export const CLEAN_PAYMENTMADE = "CLEAN_PAYMENTMADE";